// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XeGo.Services.CodeValue.API.Data;

#nullable disable

namespace XeGo.Services.CodeValue.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("XeGo.Services.CodeValue.API.Entities.CodeMetaData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value10Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value10Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value1Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value1Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value2Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value2Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value3Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value3Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value4Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value4Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value5Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value5Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value6Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value6Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value7Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value7Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value8Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value8Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value9Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value9Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CodeMetaData");
                });

            modelBuilder.Entity("XeGo.Services.CodeValue.API.Entities.CodeValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveStartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value10")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value3")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value4")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value5")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value6")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value7")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value8")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value9")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Value1");

                    b.ToTable("CodeValues");
                });
#pragma warning restore 612, 618
        }
    }
}
