version: '3.4'

services:
  authdb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  codevaluedb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  locationdb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  xego.services.auth.authapi:
    image: ${DOCKER_REGISTRY-}xegoservicesauthauthapi
    build:
      context: .
      dockerfile: Services/Auth/XeGo.Services.Auth.API/Dockerfile

  xego.services.codevalue.api:
    image: ${DOCKER_REGISTRY-}xegoservicescodevalueapi
    build:
      context: .
      dockerfile: Services/CodeValue/XeGo.Services.CodeValue.API/Dockerfile

  xego.services.codevalue.grpc:
    image: ${DOCKER_REGISTRY-}xegoservicescodevaluegrpc
    build:
      context: .
      dockerfile: Services/CodeValue/XeGo.Services.CodeValue.Grpc/Dockerfile

  xego.services.location.api:
    image: ${DOCKER_REGISTRY-}xegoserviceslocationapi
    build:
      context: .
      dockerfile: Services/Location/XeGo.Services.Location.API/Dockerfile

  xego.services.location.grpc:
    image: ${DOCKER_REGISTRY-}xegoserviceslocationgrpc
    build:
      context: .
      dockerfile: Services/Location/XeGo.Services.Location.Grpc/Dockerfile

  rabbitmq:
    image: rabbitmq:3.12-management-alpine

  portainer:
    image: portainer/portainer-ce 

  elasticsearch:
    image: elasticsearch:8.10.4

  kibana:
    image: kibana:8.10.4

volumes:
  portainer_data:
  elasticsearch-data:




