version: '3.4'

services:
  authdb:
    container_name: authdb
    environment:
        SA_PASSWORD: "admin1234@A"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-authdb:/var/opt/mssql

  codevaluedb:
    container_name: codevaluedb
    environment:
        SA_PASSWORD: "admin1234@A"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1434:1433"
    volumes:
      - sqlserver-codevaluedb:/var/opt/mssql

  locationdb:
    container_name: locationdb
    environment:
        SA_PASSWORD: "admin1234@A"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1435:1433"
    volumes:
      - sqlserver-locationdb:/var/opt/mssql

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  xego.services.auth.authapi:
    container_name: xego.services.auth.authapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=authdb;Database=XeGoAuthDb;User Id=sa;Password=admin1234@A;TrustServerCertificate=True
      - GrpcSettings__CodeValueGrpcUrl=http://xego.services.codevalue.grpc
      - ApiSettings__JwtOptions__Secret=adfh@JDFDKSAF1234sdf*%$#feifkdmvcoaerDSJFAOEDFDFJffDSAFjkAjdfA485723AjdfAJfDjfAjdfdjferYGjASDJfEjfvdav
      - ApiSettings__JwtOptions__Issuer=xego-auth-api
      - ApiSettings__JwtOptions__Audience=xego-client
      - Serilog__MinimumLevel__Default=Debug
      - Serilog__MinimumLevel__Override__Microsoft=Debug
      - Serilog__MinimumLevel__Override__System=Warning
      - ElasticConfiguration__Uri=http://elasticsearch 
    depends_on:
      - authdb
      - elasticsearch
    ports:
      - "6001:80"
      - "7001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro


  xego.services.codevalue.api:
    container_name: xego.services.codevalue.api
    environment:
      - ConnectionStrings__DefaultConnection=Server=codevaluedb;Database=XeGoCodeValueDb;User Id=sa;Password=admin1234@A;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiSettings__JwtOptions__Secret=adfh@JDFDKSAF1234sdf*%$#feifkdmvcoaerDSJFAOEDFDFJffDSAFjkAjdfA485723AjdfAJfDjfAjdfdjferYGjASDJfEjfvdav
      - ApiSettings__JwtOptions__Issuer=xego-auth-api
      - ApiSettings__JwtOptions__Audience=xego-client
      - Serilog__MinimumLevel__Default=Debug
      - Serilog__MinimumLevel__Override__Microsoft=Debug
      - Serilog__MinimumLevel__Override__System=Warning
      - ElasticConfiguration__Uri=http://elasticsearch
    depends_on:
      - codevaluedb
      - elasticsearch
    ports:
      - "6002:80"
      - "7002:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  xego.services.codevalue.grpc:
    container_name: xego.services.codevalue.grpc
    environment:
      - ConnectionStrings__DefaultConnection=Server=codevaluedb;Database=XeGoCodeValueDb;User Id=sa;Password=admin1234@A;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - Serilog__MinimumLevel__Default=Debug
      - Serilog__MinimumLevel__Override__Microsoft=Debug
      - Serilog__MinimumLevel__Override__System=Warning
      - ElasticConfiguration__Uri=http://elasticsearch
    depends_on:
      - codevaluedb
      - elasticsearch
    ports:
      - "6003:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  xego.services.location.api:
    container_name: xego.services.location.api
    environment:
      - ConnectionStrings__DefaultConnection=Server=locationdb;Database=XeGoLocation;User Id=sa;Password=admin1234@A;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - Serilog__MinimumLevel__Default=Debug
      - Serilog__MinimumLevel__Override__Microsoft=Debug
      - Serilog__MinimumLevel__Override__System=Warning
      - ApiSettings__JwtOptions__Secret=adfh@JDFDKSAF1234sdf*%$#feifkdmvcoaerDSJFAOEDFDFJffDSAFjkAjdfA485723AjdfAJfDjfAjdfdjferYGjASDJfEjfvdav
      - ApiSettings__JwtOptions__Issuer=xego-auth-api
      - ApiSettings__JwtOptions__Audience=xego-client
      - ElasticConfiguration__Uri=http://elasticsearch 
      - GrpcSettings__CodeValueGrpcUrl=http://xego.services.codevalue.grpc
    depends_on:
      - locationdb
      - xego.services.codevalue.grpc
      - elasticsearch
    ports:
      - "6004:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  xego.services.location.grpc:
    container_name: xego.services.location.grpc
    environment:
      - ConnectionStrings__DefaultConnection=Server=locationdb;Database=XeGoLocation;User Id=sa;Password=admin1234@A;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - Serilog__MinimumLevel__Default=Debug
      - Serilog__MinimumLevel__Override__Microsoft=Debug
      - Serilog__MinimumLevel__Override__System=Warning
      - ElasticConfiguration__Uri=http://elasticsearch 
      - GrpcSettings__CodeValueGrpcUrl=http://xego.services.codevalue.grpc
    depends_on:
      - locationdb
      - xego.services.codevalue.grpc
      - elasticsearch
    ports:
      - "6005:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  elasticsearch:
    container_name: elasticsearch
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - elastic

  kibana:
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=elasticsearch
    networks:
      - elastic
  
networks:
  elastic:
    driver: bridge



volumes:
  sqlserver-authdb:
  sqlserver-codevaluedb:
  sqlserver-locationdb:
  portainer_data:  
  elasticsearch-data:


