version: '3.4'

services:
  authdb:
    container_name: authdb
    environment:
        SA_PASSWORD: "admin1234@A"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-authdb:/var/opt/mssql

  # codevaluedb:
  #   container_name: codevaluedb
  #   environment:
  #       SA_PASSWORD: "admin1234@A"
  #       ACCEPT_EULA: "Y"
  #   restart: always
  #   ports:
  #     - "1434:1433"
  #   volumes:
  #     - sqlserver-codevaluedb:/var/opt/mssql

  locationdb:
    container_name: locationdb
    environment:
        SA_PASSWORD: "admin1234@A"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1435:1433"
    volumes:
      - sqlserver-locationdb:/var/opt/mssql

  vehicledb:
    container_name: vehicledb
    environment:
        SA_PASSWORD: "admin1234@A"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1436:1433"
    volumes:
      - sqlserver-vehicledb:/var/opt/mssql
  
  filedb:
    container_name: filedb
    environment:
        SA_PASSWORD: "admin1234@A"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1437:1433"
    volumes:
      - sqlserver-filedb:/var/opt/mssql

  ridedb:
    container_name: ridedb
    environment:
        SA_PASSWORD: "admin1234@A"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1438:1433"
    volumes:
      - sqlserver-ridedb:/var/opt/mssql

  notificationdb:
    container_name: notificationdb
    environment:
        SA_PASSWORD: "admin1234@A"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1439:1433"
    volumes:
      - sqlserver-notificationdb:/var/opt/mssql

  # rabbitmq:
  #   container_name: rabbitmq
  #   restart: always
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"

  xego.services.auth.api:
    container_name: xego.services.auth.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=authdb;Database=XeGoAuthDb;User Id=sa;Password=admin1234@A;TrustServerCertificate=True
      # - GrpcSettings__CodeValueGrpcUrl=http://xego.services.codevalue.grpc
      - ApiSettings__JwtOptions__Secret=adfh@JDFDKSAF1234sdf*%$$#feifkdmvcoaerDSJFAOEDFDFJffDSAFjkAjdfA485723AjdfAJfDjfAjdfdjferYGjASDJfEjfvdav
      - ApiSettings__JwtOptions__Issuer=xego-auth-api
      - ApiSettings__JwtOptions__Audience=xego-client
      - Serilog__MinimumLevel__Default=Debug
      - Serilog__MinimumLevel__Override__Microsoft=Debug
      - Serilog__MinimumLevel__Override__System=Warning
      - ElasticConfiguration__Uri=http://elasticsearch 
    depends_on:
      - authdb
      - elasticsearch
    ports:
      - "6001:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro


  # xego.services.codevalue.api:
  #   container_name: xego.services.codevalue.api
  #   environment:
  #     - ConnectionStrings__DefaultConnection=Server=codevaluedb;Database=XeGoCodeValueDb;User Id=sa;Password=admin1234@A;TrustServerCertificate=True
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ApiSettings__JwtOptions__Secret=adfh@JDFDKSAF1234sdf*%$$#feifkdmvcoaerDSJFAOEDFDFJffDSAFjkAjdfA485723AjdfAJfDjfAjdfdjferYGjASDJfEjfvdav
  #     - ApiSettings__JwtOptions__Issuer=xego-auth-api
  #     - ApiSettings__JwtOptions__Audience=xego-client
  #     - Serilog__MinimumLevel__Default=Debug
  #     - Serilog__MinimumLevel__Override__Microsoft=Debug
  #     - Serilog__MinimumLevel__Override__System=Warning
  #     - ElasticConfiguration__Uri=http://elasticsearch
  #   depends_on:
  #     - codevaluedb
  #     - elasticsearch
  #   ports:
  #     - "6002:8080"
  #     - "7002:443"
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  #     - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  # xego.services.codevalue.grpc:
  #   container_name: xego.services.codevalue.grpc
  #   environment:
  #     - ConnectionStrings__DefaultConnection=Server=codevaluedb;Database=XeGoCodeValueDb;User Id=sa;Password=admin1234@A;TrustServerCertificate=True
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - Serilog__MinimumLevel__Default=Debug
  #     - Serilog__MinimumLevel__Override__Microsoft=Debug
  #     - Serilog__MinimumLevel__Override__System=Warning
  #     - ElasticConfiguration__Uri=http://elasticsearch
  #   depends_on:
  #     - codevaluedb
  #     - elasticsearch
  #   ports:
  #     - "6003:8080"
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  #     - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  xego.services.location.api:
    container_name: xego.services.location.api
    environment:
      - ConnectionStrings__DefaultConnection=Server=locationdb;Database=XeGoLocation;User Id=sa;Password=admin1234@A;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - Serilog__MinimumLevel__Default=Debug
      - Serilog__MinimumLevel__Override__Microsoft=Debug
      - Serilog__MinimumLevel__Override__System=Warning
      - ApiSettings__JwtOptions__Secret=adfh@JDFDKSAF1234sdf*%$$#feifkdmvcoaerDSJFAOEDFDFJffDSAFjkAjdfA485723AjdfAJfDjfAjdfdjferYGjASDJfEjfvdav
      - ApiSettings__JwtOptions__Issuer=xego-auth-api
      - ApiSettings__JwtOptions__Audience=xego-client
      - ElasticConfiguration__Uri=http://elasticsearch 
      # - GrpcSettings__CodeValueGrpcUrl=http://xego.services.codevalue.grpc
    depends_on:
      - locationdb
      # - xego.services.codevalue.grpc
      - elasticsearch
    ports:
      - "6004:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  xego.services.location.grpc:
    container_name: xego.services.location.grpc
    environment:
      - ConnectionStrings__DefaultConnection=Server=locationdb;Database=XeGoLocation;User Id=sa;Password=admin1234@A;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - Serilog__MinimumLevel__Default=Debug
      - Serilog__MinimumLevel__Override__Microsoft=Debug
      - Serilog__MinimumLevel__Override__System=Warning
      - ElasticConfiguration__Uri=http://elasticsearch 
      # - GrpcSettings__CodeValueGrpcUrl=http://xego.services.codevalue.grpc
    depends_on:
      - locationdb
      # - xego.services.codevalue.grpc
      - elasticsearch
    ports:
      - "6005:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  xego.services.vehicle.api:
    container_name: xego.services.vehicle.api
    environment:
      - ConnectionStrings__DefaultConnection=Server=vehicledb;Database=XeGoVehicle;User Id=sa;Password=admin1234@A;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - Serilog__MinimumLevel__Default=Debug
      - Serilog__MinimumLevel__Override__Microsoft=Debug
      - Serilog__MinimumLevel__Override__System=Warning
      - ApiSettings__JwtOptions__Secret=adfh@JDFDKSAF1234sdf*%$$#feifkdmvcoaerDSJFAOEDFDFJffDSAFjkAjdfA485723AjdfAJfDjfAjdfdjferYGjASDJfEjfvdav
      - ApiSettings__JwtOptions__Issuer=xego-auth-api
      - ApiSettings__JwtOptions__Audience=xego-client
      - ElasticConfiguration__Uri=http://elasticsearch 
      # - GrpcSettings__CodeValueGrpcUrl=http://xego.services.codevalue.grpc
    depends_on:
      - vehicledb
      # - xego.services.codevalue.grpc
      - elasticsearch
    ports:
      - "6006:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  xego.services.file.api:
    container_name: xego.services.file.api
    environment:
    - ConnectionStrings__DefaultConnection=Server=filedb;Database=XeGoFile;User Id=sa;Password=admin1234@A;TrustServerCertificate=True
    - ASPNETCORE_ENVIRONMENT=Development
    - Serilog__MinimumLevel__Default=Debug
    - Serilog__MinimumLevel__Override__Microsoft=Debug
    - Serilog__MinimumLevel__Override__System=Warning
    - ApiSettings__JwtOptions__Secret=adfh@JDFDKSAF1234sdf*%$$#feifkdmvcoaerDSJFAOEDFDFJffDSAFjkAjdfA485723AjdfAJfDjfAjdfdjferYGjASDJfEjfvdav
    - ApiSettings__JwtOptions__Issuer=xego-auth-api
    - ApiSettings__JwtOptions__Audience=xego-client
    - ElasticConfiguration__Uri=http://elasticsearch 
    - BlobConnection=DefaultEndpointsProtocol=https;AccountName=xegomedia;AccountKey=VrFXM/Zn63So11j47jRT+f36LhLRQJyNOLY7Wl4cpt/30IYvPGxp2rkdEVHsXZcemf3Au8qBynCS+AStY/XcPw==;EndpointSuffix=core.windows.net
    # - GrpcSettings__CodeValueGrpcUrl=http://xego.services.codevalue.grpc
    secrets:
    - blob_connection
    depends_on:
    - filedb
    # - xego.services.codevalue.grpc
    - elasticsearch
    ports:
    - "6007:8080"
    volumes:
    - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  xego.services.ride.api:
    container_name: xego.services.ride.api
    environment:
      - ConnectionStrings__DefaultConnection=Server=ridedb;Database=XeGoRide;User Id=sa;Password=admin1234@A;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - Serilog__MinimumLevel__Default=Debug
      - Serilog__MinimumLevel__Override__Microsoft=Debug
      - Serilog__MinimumLevel__Override__System=Warning
      - ApiSettings__JwtOptions__Secret=adfh@JDFDKSAF1234sdf*%$$#feifkdmvcoaerDSJFAOEDFDFJffDSAFjkAjdfA485723AjdfAJfDjfAjdfdjferYGjASDJfEjfvdav
      - ApiSettings__JwtOptions__Issuer=xego-auth-api
      - ApiSettings__JwtOptions__Audience=xego-client
      - ElasticConfiguration__Uri=http://elasticsearch 
    ports:
      - "6008:8080"
    depends_on:
      - ridedb

  xego.services.notifications.functions:
    container_name: xego.services.notifications.functions
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AzureWebJobsStorage=DefaultEndpointsProtocol=https;AccountName=xegoazurewebjobsstorage;AccountKey=ZUU0wCqXsxnAU3OknEtQg9G+kzSQdv7PiSi95Qq+hE6fTGHQoDWfuqMKKmIo1OcgS+JOLJHL15lN+ASt5cmGzA==;EndpointSuffix=core.windows.net
      - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
      - TwilioAccountSid=AC37acf87c41f3c6e35391e6220530c380
      - TwilioAuthToken=2f9df0e12cf21ec1e4c1580d906af3bb
      - TwilioPhoneNumber=+17472221843
      - SqlDbConnection=Server=notificationdb;Database=XeGoNotification;User Id=sa;Password=admin1234@A;TrustServerCertificate=True
      - ApiSettings__JwtOptions__Secret=adfh@JDFDKSAF1234sdf*%$#feifkdmvcoaerDSJFAOEDFDFJffDSAFjkAjdfA485723AjdfAJfDjfAjdfdjferYGjASDJfEjfvdav
      - ApiSettings__JwtOptions__Issuer=xego-auth-api
      - ApiSettings__JwtOptions__Audience=xego-client
      - Serilog__MinimumLevel__Default=Debug
      - Serilog__MinimumLevel__Override__Microsoft=Debug
      - Serilog__MinimumLevel__Override__System=Warning 
      - ElasticConfiguration__Uri=http://elasticsearch 
    ports:
      - "6009:8080"
    depends_on:
      - notificationdb
    secrets:
      - azure_web_jobs_storage
      - twilio_account_sid
      - twilio_auth_token
      - twilio_phone_number

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  elasticsearch:
    container_name: elasticsearch
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - elastic

  kibana:
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=elasticsearch
    networks:
      - elastic


  xego.apigateways.ocelot:
    container_name: xego.apigateways.ocelot
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Serilog__MinimumLevel__Default=Debug
      - Serilog__MinimumLevel__Override__Microsoft=Debug
      - Serilog__MinimumLevel__Override__System=Warning
      - ApiSettings__JwtOptions__Secret=adfh@JDFDKSAF1234sdf*%$$#feifkdmvcoaerDSJFAOEDFDFJffDSAFjkAjdfA485723AjdfAJfDjfAjdfdjferYGjASDJfEjfvdav
      - ApiSettings__JwtOptions__Issuer=xego-auth-api
      - ApiSettings__JwtOptions__Audience=xego-client
      - ElasticConfiguration__Uri=http://elasticsearch
    ports:
      - "6100:8080"
    depends_on:
      - elasticsearch
      - xego.services.auth.api
      # - xego.services.codevalue.api
      - xego.services.location.api
      - xego.services.vehicle.api
      - xego.services.file.api

networks:
  elastic:
    driver: bridge


secrets:
  blob_connection:
    file: ./secrets/blob_connection.txt
  azure_web_jobs_storage:
    file: ./secrets/azure_web_jobs_storage.txt
  twilio_account_sid:
    file: ./secrets/twilio_account_sid.txt
  twilio_auth_token:
    file: ./secrets/twilio_auth_token.txt
  twilio_phone_number:
    file: ./secrets/twilio_phone_number.txt

volumes:
  sqlserver-authdb:
  # sqlserver-codevaluedb:
  sqlserver-locationdb:
  sqlserver-vehicledb:
  sqlserver-filedb:
  sqlserver-ridedb:
  sqlserver-notificationdb:
  portainer_data:  
  elasticsearch-data:







