// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmC7sws14LpkvLMpkxwkPoPQ597vP0_JQ',
    appId: '1:983938356743:web:aa94b7afec9612a4c57ca2',
    messagingSenderId: '983938356743',
    projectId: 'xego-404112',
    authDomain: 'xego-404112.firebaseapp.com',
    storageBucket: 'xego-404112.appspot.com',
    measurementId: 'G-13PXD9NPH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs83Q7Kbs-p4wxlYrx6LQUahWeA_jYgmI',
    appId: '1:983938356743:android:adeb02a2d42ecd38c57ca2',
    messagingSenderId: '983938356743',
    projectId: 'xego-404112',
    storageBucket: 'xego-404112.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFQK0caq8Ewd6FmM4YFOBVYhoQ6xkziY0',
    appId: '1:983938356743:ios:211545d1a90b0664c57ca2',
    messagingSenderId: '983938356743',
    projectId: 'xego-404112',
    storageBucket: 'xego-404112.appspot.com',
    iosBundleId: 'com.example.xegoDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFQK0caq8Ewd6FmM4YFOBVYhoQ6xkziY0',
    appId: '1:983938356743:ios:07e29f4d80ed185ec57ca2',
    messagingSenderId: '983938356743',
    projectId: 'xego-404112',
    storageBucket: 'xego-404112.appspot.com',
    iosBundleId: 'com.example.xegoDriver.RunnerTests',
  );
}
